### ISSUE TITLE
Use **name** to filter `Pricing Policy` instead of using **id**

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfchain_explorer#138]
Currently, We're using **id** to filter `pricing policy` however ids doesn't make sense from the user perspective so we should update this filter to use **name** instead.

However graphql api doesn't return names back as shown below
![image](https://user-images.githubusercontent.com/31689104/149903954-d14eac42-ea3a-4901-9fd7-91f0c740ba2d.png)

**Comment by DylanVerstraete** [comment]
Pricing policies are not stored on graphql (yet), only when a new pricing policy is created it will be picked up and stored on graphql. This is because the initial pricing policies are stored in the genesis config and graphql cannot see an event for that becuase there was no event for it. I suggest fetching the pricing policies from chain and comparing that way

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/tfchain_explorer/pull/140

**Comment by RafyAmgadBenjamin** [comment]
### Verified on 
[`explorer.dev.grid.tf`
](https://explorer.dev.grid.tf/nodes)

![image](https://user-images.githubusercontent.com/46320202/155344280-a6de14a1-1099-413f-ba98-4c23bed2851c.png)
